# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task_service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12task_service.proto\x12\x0ctask_service\"I\n\x11\x43reateTaskRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x10\n\x08\x64\x65\x61\x64line\x18\x03 \x01(\t\"\x1f\n\rTaskIdRequest\x12\x0e\n\x06taskId\x18\x01 \x01(\x05\"n\n\x11UpdateTaskRequest\x12\x0e\n\x06taskId\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x10\n\x08\x64\x65\x61\x64line\x18\x04 \x01(\t\x12\x13\n\x0bisCompleted\x18\x05 \x01(\x08\"%\n\x12\x44\x65leteTaskResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"}\n\x0cTaskResponse\x12\x0e\n\x06taskId\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x12\n\ncreated_at\x18\x04 \x01(\t\x12\x10\n\x08\x64\x65\x61\x64line\x18\x05 \x01(\t\x12\x13\n\x0bisCompleted\x18\x06 \x01(\x08\"2\n\x10ListTasksRequest\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x10\n\x08pageSize\x18\x02 \x01(\x05\">\n\x11ListTasksResponse\x12)\n\x05tasks\x18\x01 \x03(\x0b\x32\x1a.task_service.TaskResponse2\x82\x03\n\x0bTaskService\x12I\n\nCreateTask\x12\x1f.task_service.CreateTaskRequest\x1a\x1a.task_service.TaskResponse\x12I\n\nUpdateTask\x12\x1f.task_service.UpdateTaskRequest\x1a\x1a.task_service.TaskResponse\x12K\n\nDeleteTask\x12\x1b.task_service.TaskIdRequest\x1a .task_service.DeleteTaskResponse\x12\x42\n\x07GetTask\x12\x1b.task_service.TaskIdRequest\x1a\x1a.task_service.TaskResponse\x12L\n\tListTasks\x12\x1e.task_service.ListTasksRequest\x1a\x1f.task_service.ListTasksResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'task_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CREATETASKREQUEST']._serialized_start=36
  _globals['_CREATETASKREQUEST']._serialized_end=109
  _globals['_TASKIDREQUEST']._serialized_start=111
  _globals['_TASKIDREQUEST']._serialized_end=142
  _globals['_UPDATETASKREQUEST']._serialized_start=144
  _globals['_UPDATETASKREQUEST']._serialized_end=254
  _globals['_DELETETASKRESPONSE']._serialized_start=256
  _globals['_DELETETASKRESPONSE']._serialized_end=293
  _globals['_TASKRESPONSE']._serialized_start=295
  _globals['_TASKRESPONSE']._serialized_end=420
  _globals['_LISTTASKSREQUEST']._serialized_start=422
  _globals['_LISTTASKSREQUEST']._serialized_end=472
  _globals['_LISTTASKSRESPONSE']._serialized_start=474
  _globals['_LISTTASKSRESPONSE']._serialized_end=536
  _globals['_TASKSERVICE']._serialized_start=539
  _globals['_TASKSERVICE']._serialized_end=925
# @@protoc_insertion_point(module_scope)
