openapi: '3.0.0'

info:
  title: 'User Service API'
  version: '1.0.0'
  description: API для управления учетными записями пользователей

servers:
  - url: 'http://localhost:5000'

paths:
  /api/users/register:
    post:
      summary: 'Регистрация нового пользователя'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        '201':
          description: 'Пользователь успешно зарегистрирован'

  /api/users/auth:
    post:
      summary: 'Аутентификация пользователя'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        '200':
          description: 'Аутентификация успешна, возвращается токен доступа'
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string

        '401':
          description: 'Неверный логин или пароль'

  /api/users/me:
    put:
      summary: 'Обновление данных пользователя'
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
                birthdate:
                  type: string
                  format: date
                email:
                  type: string
                  format: email
                phone_number:
                  type: string
              required: []
      responses:
        '200':
          description: 'Данные пользователя успешно обновлены'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
